"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

// Bridge needs to be loaded explicitly, before
// loading any module generated by Bridge.
require("../dist/bridge/bridge");

// Load MathModule generated by Bridge.
const mathModule = require("../dist/bridge/TSProjDemo.Bridge").MathModule;

// Load other modules.
const rl = require("readline-sync");

class MathDemo {
    Run() {
        console.log("*** Math Expression Evaluaton Demo ***");
        console.log("   (enter an empty string to exit)");
        console.log("");
        console.log("Sample: (1 + 2) * 3");
        console.log("Result: 9");
        console.log("");

        // Create an instance of Evaluator:
        const evaluator = new mathModule.TSProjDemo.Bridge.Evaluator();

        let expr;
        while ((expr = rl.question("Math Expression: ")).length > 0) {
            try {
                // Evaluate:
                var res = evaluator.Evaluate(expr);
                console.log("Result: " + res);
            } catch (err) {
                console.log("[Error]: " + err.message);
            }
            console.log("");
        }
    }
}

exports.MathDemo = MathDemo;
